import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'settings': 'Settings',
      'general': 'General',
      'app_language': 'App Language',
      'time_zone': 'Time Zone',
      'date_format': 'Date Format',
      'appearance': 'Appearance',
      'dark_mode': 'Dark Mode',
      'font_size': 'Font Size',
      'audio_ai': 'Audio & AI',
      'voice_response': 'Voice Response',
      'default_ai_mode': 'Default AI Mode',
      'safety': 'Safety',
      'emergency_contact': 'Emergency Contact',
      'support': 'Support',
      'faq': 'FAQ',
      'contact_support': 'Contact Support',
      'feedback': 'Feedback / Report Problem',
      'privacy_data': 'Privacy & Data',
      'consent_data': 'Consent & Data Usage',
      'delete_account': 'Delete Account',
      'about': 'About',
      'terms': 'Terms & Conditions',
      'privacy_policy': 'Privacy Policy',
      'licenses': 'Licenses',
      'save': 'Save',
      'cancel': 'Cancel',
      'not_set': 'Not set',
      'home': 'Home',
      'reminders': 'Reminders',
      'profile': 'Profile',
      'ai_chat': 'AI Chat',
      'find_doctors': 'Find Doctors',
      'analysis': 'Analysis',
      'companion': 'Companion',
      'welcome_back': 'Welcome back,',
      'create_avatar': 'Create Avatar',
      'manage_avatar': 'Manage Avatar',
      'reminder_alert': 'Reminder / Alert',
      'add_reminder': 'Add Reminder',
      'edit_reminder': 'Edit Reminder',
      'title': 'Title',
      'description_optional': 'Description (Optional)',
      'date': 'Date',
      'time': 'Time',
      'repeat': 'Repeat',
      'vibration': 'Vibration',
      'vibrate_desc': 'Vibrate when reminder triggers',
      'save_reminder': 'SAVE REMINDER',
      'enter_title': 'Enter reminder title',
      'enter_desc': 'Enter description',
      'today_only': 'Today Only',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'err_title': 'Please enter a title',
      'err_future': 'Please select a time in the future',
      'msg_updated': 'Reminder updated!',
      'msg_saved': 'Reminder saved successfully!',
      'mental_health_analysis': 'Mental Health Analysis',
      'emotional_overview': 'Emotional Overview',
      'time_based_analysis': 'Time-Based Analysis',
      'daily_mood_timeline': 'Daily Mood Timeline',
      'mental_health_score': 'Mental Health Score',
      'no_data': 'No data available',
      'no_emotional_data': 'No emotional data recorded yet.',
      'no_timeline_data': 'No timeline data available.',
      'out_of_100': 'out of 100',
      'score_desc': 'Based on your recent interactions and emotional patterns.',
      'excellent': 'Excellent',
      'good': 'Good',
      'fair': 'Fair',
      'needs_attention': 'Needs Attention',
      'positive': 'Positive',
      'negative': 'Negative',
      'morning': 'Morning',
      'afternoon': 'Afternoon',
      'evening': 'Evening',
      'night': 'Night',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'last_7_days': 'Last 7 Days',
      'last_30_days': 'Last 30 Days',
      'this_month': 'This Month',
      'last_month': 'Last Month',
      'all_time': 'All Time',
      'find_doctors_title': 'Find Doctors',
      'no_doctors': 'No doctors found nearby.',
      'view': 'View',
      'rating': 'Rating',
      'yrs': 'Yrs',
      'address': 'Address',
      'availability': 'Availability',
      'book_appointment': 'BOOK APPOINTMENT',
      'yrs_exp': 'yrs exp',
      'funny': 'Funny',
      'search': 'Search',
      'mental_health': 'Mental Health',
      'study': 'Study',
      'no_history': 'No history for this mode',
      'untitled_chat': 'Untitled Chat',
      'no_msg_share': 'No messages to share',
      'share_chat_as': 'Share Chat As',
      'text_format': 'Text Format',
      'pdf_format': 'PDF Format',
      'select_chat_mode': 'Select Chat Mode',
      'ai_chat_title': 'AI Chat',
      'voice_reply': 'Voice Reply',
      'select_voice': 'Select Voice',
      'new_chat': 'New Chat',
      'chat_history': 'Chat History',
      'back_to_chat': 'Back to Chat',
      'view_analysis': 'View Analysis',
      'download_chat': 'Download Chat',
      'share_chat': 'Share Chat',
      'type_message': 'Type a message...',
      'select_mode': 'Select Mode',
      'stop_listening': 'Stop Listening',
      'start_listening': 'Start Listening',
      'female': 'Female',
      'male': 'Male',
      'no_system_voices': 'No system voices found. Please check your device settings.',
      'selected_voice_msg': 'Selected voice: ',
      'preview_failed': 'Preview failed: ',
      'no_voices_available': 'No voices available',
      'unknown': 'Unknown',
      'select': 'Select',
      'retry': 'Retry',
      'hello_voice': 'Hello, I am {name}. How can I help you today?',
      'email': 'Email',
      'phone': 'Phone',
      'dob': 'Date of Birth',
      'user_name': 'User Name',
      'edit_profile': 'Edit Profile',
      'tap_to_change': 'Tap to change photo',
      'username': 'Username',
      'phone_number': 'Phone Number',
      'save_changes': 'SAVE CHANGES',
      'profile_updated': 'Profile updated successfully!',
      'failed_update': 'Failed to update profile',
      'enter_username': 'Please enter username',
      'enter_email': 'Please enter email',
      'enter_valid_email': 'Please enter a valid email',
      'enter_phone': 'Please enter phone number',
      'select_dob': 'Please select date of birth',
      'relationship': 'Relationship',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'delete_account_confirm': 'Are you sure you want to delete your account? This action cannot be undone and all your data will be lost.',
      'account_deleted': 'Account deleted successfully.',
      'failed_delete_account': 'Failed to delete account.',
      'app_version': 'App Version',
      'analysis_dashboard': 'Analysis Dashboard',
      'insights': 'Insights',
      'positive': 'Positive',
      'negative': 'Negative',
      'mostly_positive_msg': 'Great job! Keep up the positive vibes! 😊',
      'mostly_negative_msg': 'A bit challenging? That\'s okay, keep going! 💪',
      'emotion_trend': 'Emotion Trend Over Time',
      'daily_mood_timeline': 'Daily Mood Timeline',
      'score': 'Score',
      'excellent': 'Excellent',
      'good': 'Good',
      'moderate': 'Moderate',
      'needs_attention': 'Needs Attention',
      'score_basis': 'Based on your recent interactions.',
      'no_data': 'No data for this period',
      'morning': 'Morning',
      'afternoon': 'Afternoon',
      'evening': 'Evening',
      'night': 'Night',
      'happy': 'Happy',
      'sad': 'Sad',
      'angry': 'Angry',
      'calm': 'Calm',
      'no_avatar_selected': 'No Avatar Selected',
      'default_avatar_msg': 'Hi! I\'m here to help.',
      'select_avatar': 'Select Avatar',
      'no_avatars_found': 'No avatars found.\nCreate one to get started!',
      'avatar_set_active': 'Avatar set as active!',
      'avatar_deleted': 'Avatar deleted successfully',
      'delete_avatar_confirm': 'Are you sure you want to delete this avatar?',
      'create_new_avatar': 'CREATE NEW AVATAR',
      'error_fetching_avatars': 'Error fetching avatars',
      'error_setting_active_avatar': 'Error setting active avatar',
      'error_deleting_avatar': 'Error deleting avatar',
      'create_your_avatar': 'Create Your Avatar',
      'error_saving_avatar': 'Error saving avatar',
      'close_and_go_home': 'Close and go to Home',
      'my_new_avatar': 'My New Avatar',
      'select_ai_mode': 'Select AI Mode',
      'funny_desc': 'AI with a sense of humor and jokes.',
      'search_desc': 'Focused on finding facts and info.',
      'mental_health_desc': 'Empathetic and supportive listener.',
      'study_desc': 'Helps with learning and explanations.',
      'snooze': 'Snooze',
      'stop': 'Stop',
      'minutes': 'minutes',
      'reminder_msg_prefix': 'This is your reminder',
      'intelligent_companion': 'Your Intelligent Companion',
      'mic_access': 'Microphone Access',
      'mic_desc': 'We need microphone access so your Avatar Companion can listen and respond to you.',
      'notif_access': 'Notifications',
      'notif_desc': 'Enable notifications to receive important reminders and alerts from your companion.',
      'overlay_access': 'Display Over Apps',
      'overlay_desc': 'Allow the Avatar to appear over other apps when a reminder triggers, even on the lock screen.',
      'battery_access': 'Battery Optimization',
      'battery_desc': 'To ensure reminders ring on time, please allow the app to run in the background without restrictions.',
      'alarm_access': 'Exact Alarms',
      'alarm_desc': 'To ensure your reminders trigger exactly on time, please allow the app to set exact alarms.',
      'location_access': 'Location Access',
      'location_desc': 'Optional: We use your location to help you find nearby doctors and services.',
      'allow_access': 'Allow Access',
      'skip_for_now': 'Skip for now',
      'no_thanks': 'No thanks',
      'permission_required': 'Permission Required',
      'permission_desc': 'This feature requires permission to function. Please enable it in app settings.',
      'permissions_required_reminder': 'Permissions are required to create reminders. Please grant the necessary permissions.',
      'open_settings': 'Open Settings',
      'sign_in_continue': 'Sign in to continue',
      'login_failed': 'Login failed',
      'enter_email': 'Please enter email',
      'enter_valid_email': 'Please enter a valid email',
      'enter_password': 'Please enter password',
      'password_min_length': 'Password must be at least 6 characters',
      'no_account_signup': "Don't have an account? Sign Up",
      'login_caps': 'LOGIN',
      'create_account': 'Create Account',
      'join_start_chatting': 'Join us to start chatting',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'enter_name': 'Please enter your name',
      'enter_phone': 'Please enter phone number',
      'enter_valid_phone': 'Please enter a valid 10-digit phone number',
      'select_dob': 'Please select your DOB',
      'registration_success': 'Registration successful!',
      'registration_failed': 'Registration failed',
      'already_account_signin': 'Already have an account? Sign In',
      'register_caps': 'REGISTER',
      'avatars': 'Avatars',
      'active': 'Active',
      'exit': 'Exit',
      'no_chat_history': 'No chat history found.',
      'chat_downloaded_preview': 'Chat Downloaded (Preview)',
      'delete_chat': 'Delete Chat',
      'delete_chat_confirm': 'Are you sure you want to delete this chat history?',
      'conversation_deleted': 'Conversation deleted',
      'no_reminders_set': 'No reminders set.',
      'repeat_none': 'Repeat: None',
      'edit': 'Edit',
      'delete': 'Delete',
      'reminder_deleted': 'Reminder deleted',
      'chat': 'Chat',
      'searching': 'Searching',
      'this_week': 'This Week',
      'last_week': 'Last Week',
      'you': 'You',
      'ai': 'AI',
      'chat_conversation_subject': 'My AI Chat Conversation',
      'chat_conversation_header': 'AI Chat Conversation',
      'notifications': 'Notifications',
      'no_notifications': 'No new notifications',
      'delete_selected': 'Delete Selected',
      'select_all': 'Select All',
      'deselect_all': 'Deselect All',
      'items_selected': 'items selected',
      'sensitive_alert': 'Sensitive Alert',
      'risk_level': 'Risk Level',
      'category': 'Category',
      'timestamp': 'Timestamp',
      'detected_language': 'Detected Language',
      'doctor_suggestion_msg': 'I\'m here for you. Would you like to book a doctor appointment to talk more about this?',
      'book_now': 'BOOK NOW',
    },
    'es': {
      'settings': 'Ajustes',
      'general': 'General',
      'app_language': 'Idioma de la aplicación',
      'time_zone': 'Zona horaria',
      'date_format': 'Formato de fecha',
      'appearance': 'Apariencia',
      'dark_mode': 'Modo oscuro',
      'font_size': 'Tamaño de fuente',
      'audio_ai': 'Audio e IA',
      'voice_response': 'Respuesta de voz',
      'default_ai_mode': 'Modo IA predeterminado',
      'safety': 'Seguridad',
      'emergency_contact': 'Contacto de emergencia',
      'support': 'Soporte',
      'faq': 'Preguntas frecuentes',
      'contact_support': 'Contactar soporte',
      'feedback': 'Comentarios / Reportar problema',
      'privacy_data': 'Privacidad y datos',
      'consent_data': 'Consentimiento y uso de datos',
      'delete_account': 'Eliminar cuenta',
      'about': 'Acerca de',
      'terms': 'Términos y condiciones',
      'privacy_policy': 'Política de privacidad',
      'licenses': 'Licencias',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'not_set': 'No establecido',
      'home': 'Inicio',
      'reminders': 'Recordatorios',
      'profile': 'Perfil',
      'ai_chat': 'Chat de IA',
      'find_doctors': 'Buscar médicos',
      'analysis': 'Análisis',
      'companion': 'Compañero',
      'welcome_back': 'Bienvenido de nuevo,',
      'create_avatar': 'Crear Avatar',
      'manage_avatar': 'Gestionar Avatar',
      'reminder_alert': 'Recordatorio / Alerta',
      'add_reminder': 'Añadir Recordatorio',
      'edit_reminder': 'Editar Recordatorio',
      'title': 'Título',
      'description_optional': 'Descripción (Opcional)',
      'date': 'Fecha',
      'time': 'Hora',
      'repeat': 'Repetir',
      'vibration': 'Vibración',
      'vibrate_desc': 'Vibrar cuando se active el recordatorio',
      'save_reminder': 'GUARDAR RECORDATORIO',
      'enter_title': 'Introduce el título del recordatorio',
      'enter_desc': 'Introduce la descripción',
      'today_only': 'Solo hoy',
      'daily': 'Diariamente',
      'weekly': 'Semanalmente',
      'monthly': 'Mensualmente',
      'err_title': 'Por favor, introduce un título',
      'err_future': 'Por favor, selecciona una hora futura',
      'msg_updated': '¡Recordatorio actualizado!',
      'msg_saved': '¡Recordatorio guardado con éxito!',
      'mental_health_analysis': 'Análisis de Salud Mental',
      'emotional_overview': 'Resumen Emocional',
      'time_based_analysis': 'Análisis Basado en el Tiempo',
      'daily_mood_timeline': 'Línea de Tiempo de Estado de Ánimo Diario',
      'mental_health_score': 'Puntuación de Salud Mental',
      'no_data': 'No hay datos disponibles',
      'no_emotional_data': 'Aún no se han registrado datos emocionales.',
      'no_timeline_data': 'No hay datos de línea de tiempo disponibles.',
      'out_of_100': 'de 100',
      'score_desc': 'Basado en tus interacciones recientes y patrones emocionales.',
      'excellent': 'Excelente',
      'good': 'Bueno',
      'fair': 'Regular',
      'needs_attention': 'Necesita Atención',
      'positive': 'Positivo',
      'negative': 'Negativo',
      'morning': 'Mañana',
      'afternoon': 'Tarde',
      'evening': 'Tarde/Noche',
      'night': 'Noche',
      'today': 'Hoy',
      'yesterday': 'Ayer',
      'last_7_days': 'Últimos 7 días',
      'last_30_days': 'Últimos 30 días',
      'this_month': 'Este mes',
      'last_month': 'Mes pasado',
      'all_time': 'Todo el tiempo',
      'find_doctors_title': 'Buscar Médicos',
      'no_doctors': 'No se encontraron médicos cerca.',
      'view': 'Ver',
      'rating': 'Calificación',
      'yrs': 'Años',
      'address': 'Dirección',
      'availability': 'Disponibilidad',
      'book_appointment': 'RESERVAR CITA',
      'yrs_exp': 'años de exp',
      'funny': 'Divertido',
      'search': 'Buscar',
      'mental_health': 'Salud Mental',
      'study': 'Estudiar',
      'no_history': 'No hay historial para este modo',
      'untitled_chat': 'Chat sin título',
      'no_msg_share': 'No hay mensajes para compartir',
      'share_chat_as': 'Compartir chat como',
      'text_format': 'Formato de texto',
      'pdf_format': 'Formato PDF',
      'select_chat_mode': 'Seleccionar modo de chat',
      'ai_chat_title': 'Chat de IA',
      'voice_reply': 'Respuesta de voz',
      'select_voice': 'Seleccionar voz',
      'new_chat': 'Nuevo chat',
      'chat_history': 'Historial de chat',
      'back_to_chat': 'Volver al chat',
      'view_analysis': 'Ver análisis',
      'download_chat': 'Descargar chat',
      'share_chat': 'Compartir chat',
      'type_message': 'Escribe un mensaje...',
      'select_mode': 'Seleccionar modo',
      'stop_listening': 'Detener escucha',
      'start_listening': 'Empezar a escuchar',
      'female': 'Femenino',
      'male': 'Masculino',
      'no_system_voices': 'No se encontraron voces del sistema. Por favor, compruebe los ajustes de su dispositivo.',
      'selected_voice_msg': 'Voz seleccionada: ',
      'preview_failed': 'Error en la vista previa: ',
      'no_voices_available': 'No hay voces disponibles',
      'unknown': 'Desconocido',
      'select': 'Seleccionar',
      'retry': 'Reintentar',
      'hello_voice': 'Hola, soy {name}. ¿Cómo puedo ayudarte hoy?',
      'email': 'Correo electrónico',
      'phone': 'Teléfono',
      'dob': 'Fecha de nacimiento',
      'user_name': 'Nombre de usuario',
      'edit_profile': 'Editar perfil',
      'tap_to_change': 'Toca para cambiar la foto',
      'username': 'Nombre de usuario',
      'phone_number': 'Número de teléfono',
      'save_changes': 'GUARDAR CAMBIOS',
      'profile_updated': '¡Perfil actualizado con éxito!',
      'failed_update': 'Error al actualizar el perfil',
      'enter_username': 'Por favor, ingrese el nombre de usuario',
      'enter_email': 'Por favor, ingrese el correo electrónico',
      'enter_valid_email': 'Por favor, ingrese un correo electrónico válido',
      'enter_phone': 'Por favor, ingrese el número de teléfono',
      'select_dob': 'Por favor, seleccione la fecha de nacimiento',
      'relationship': 'Relación',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'delete': 'Eliminar',
      'delete_account_confirm': '¿Está seguro de que desea eliminar su cuenta? Esta acción no se puede deshacer y todos sus datos se perderán.',
      'account_deleted': 'Cuenta eliminada con éxito.',
      'failed_delete_account': 'Error al eliminar la cuenta.',
      'app_version': 'Versión de la aplicación',
      'analysis_dashboard': 'Panel de análisis',
      'insights': 'Perspectivas',
      'positive': 'Positivo',
      'negative': 'Negativo',
      'mostly_positive_msg': '¡Buen trabajo! ¡Sigue con las vibras positivas! 😊',
      'mostly_negative_msg': '¿Un poco desafiante? ¡Está bien, sigue adelante! 💪',
      'emotion_trend': 'Tendencia emocional a lo largo del tiempo',
      'daily_mood_timeline': 'Línea de tiempo del estado de ánimo diario',
      'score': 'Puntuación',
      'excellent': 'Excelente',
      'good': 'Bueno',
      'moderate': 'Moderado',
      'needs_attention': 'Necesita atención',
      'score_basis': 'Basado en sus interacciones recientes.',
      'no_data': 'No hay datos para este período',
      'morning': 'Mañana',
      'afternoon': 'Tarde',
      'evening': 'Noche',
      'night': 'Noche',
      'happy': 'Feliz',
      'sad': 'Triste',
      'angry': 'Enojado',
      'calm': 'Calma',
      'no_avatar_selected': 'Ningún avatar seleccionado',
      'default_avatar_msg': '¡Hola! Estoy aquí para ayudar.',
      'select_avatar': 'Seleccionar avatar',
      'no_avatars_found': 'No se encontraron avatares.\n¡Crea uno para comenzar!',
      'avatar_set_active': '¡Avatar establecido como activo!',
      'avatar_deleted': 'Avatar eliminado con éxito',
      'delete_avatar_confirm': '¿Estás seguro de que quieres eliminar este avatar?',
      'create_new_avatar': 'CREAR NUEVO AVATAR',
      'error_fetching_avatars': 'Error al obtener avatares',
      'error_setting_active_avatar': 'Error al establecer el avatar activo',
      'error_deleting_avatar': 'Error al eliminar el avatar',
      'create_your_avatar': 'Crea tu avatar',
      'error_saving_avatar': 'Error al guardar el avatar',
      'close_and_go_home': 'Cerrar e ir a Inicio',
      'my_new_avatar': 'Mi nuevo avatar',
      'select_ai_mode': 'Seleccionar modo de IA',
      'funny_desc': 'IA con sentido del humor y chistes.',
      'search_desc': 'Enfocado en encontrar hechos e información.',
      'mental_health_desc': 'Oyente empático y solidario.',
      'study_desc': 'Ayuda con el aprendizaje y las explicaciones.',
      'snooze': 'Posponer',
      'stop': 'Detener',
      'minutes': 'minutos',
      'reminder_msg_prefix': 'Este es tu recordatorio',
      'intelligent_companion': 'Tu compañero inteligente',
      'mic_access': 'Acceso al micrófono',
      'mic_desc': 'Necesitamos acceso al micrófono para que tu compañero avatar pueda escucharte y responderte.',
      'notif_access': 'Notificaciones',
      'notif_desc': 'Habilita las notificaciones para recibir recordatorios y alertas importantes de tu compañero.',
      'overlay_access': 'Mostrar sobre otras aplicaciones',
      'overlay_desc': 'Permite que el avatar aparezca sobre otras aplicaciones cuando se activa un recordatorio, incluso en la pantalla de bloqueo.',
      'battery_access': 'Optimización de batería',
      'battery_desc': 'Para asegurar que los recordatorios suenen a tiempo, permite que la aplicación se ejecute en segundo plano sin restricciones.',
      'alarm_access': 'Alarmas exactas',
      'alarm_desc': 'Para asegurar que tus recordatorios se activen exactamente a tiempo, permite que la aplicación establezca alarmas exactas.',
      'location_access': 'Acceso a la ubicación',
      'location_desc': 'Opcional: Utilizamos tu ubicación para ayudarte a encontrar médicos y servicios cercanos.',
      'allow_access': 'Permitir acceso',
      'skip_for_now': 'Omitir por ahora',
      'no_thanks': 'No, gracias',
      'permission_required': 'Permiso requerido',
      'permission_desc': 'Esta función requiere permiso para funcionar. Por favor, habilítalo en los ajustes de la aplicación.',
      'permissions_required_reminder': 'Se requieren permisos para crear recordatorios. Por favor, otorga los permisos necesarios.',
      'open_settings': 'Abrir ajustes',
      'sign_in_continue': 'Inicia sesión para continuar',
      'login_failed': 'Error al iniciar sesión',
      'enter_email': 'Por favor, introduce el correo electrónico',
      'enter_valid_email': 'Por favor, introduce un correo electrónico válido',
      'enter_password': 'Por favor, introduce la contraseña',
      'password_min_length': 'La contraseña debe tener al menos 6 caracteres',
      'no_account_signup': "¿No tienes una cuenta? Regístrate",
      'login_caps': 'INICIAR SESIÓN',
      'create_account': 'Crear cuenta',
      'join_start_chatting': 'Únete a nosotros para empezar a chatear',
      'full_name': 'Nombre completo',
      'phone_number': 'Número de teléfono',
      'enter_name': 'Por favor, introduce tu nombre',
      'enter_phone': 'Por favor, introduce el número de teléfono',
      'enter_valid_phone': 'Por favor, introduce un número de teléfono válido de 10 dígitos',
      'select_dob': 'Por favor, selecciona tu fecha de nacimiento',
      'registration_success': '¡Registro exitoso!',
      'registration_failed': 'Error al registrarse',
      'already_account_signin': '¿Ya tienes una cuenta? Inicia sesión',
      'register_caps': 'REGISTRARSE',
      'avatars': 'Avatares',
      'active': 'Activo',
      'exit': 'Salir',
      'no_chat_history': 'No se encontró historial de chat.',
      'chat_downloaded_preview': 'Chat descargado (Vista previa)',
      'delete_chat': 'Eliminar chat',
      'delete_chat_confirm': '¿Estás seguro de que deseas eliminar este historial de chat?',
      'conversation_deleted': 'Conversación eliminada',
      'no_reminders_set': 'No hay recordatorios configurados.',
      'repeat_none': 'Repetir: Ninguno',
      'edit': 'Editar',
      'delete': 'Eliminar',
      'reminder_deleted': 'Recordatorio eliminado',
      'chat': 'Chat',
      'searching': 'Buscando',
      'this_week': 'Esta semana',
      'last_week': 'La semana pasada',
      'you': 'Tú',
      'ai': 'IA',
      'chat_conversation_subject': 'Mi conversación de chat de IA',
      'chat_conversation_header': 'Conversación de chat de IA',
      'notifications': 'Notificaciones',
      'no_notifications': 'No hay nuevas notificaciones',
      'delete_selected': 'Eliminar seleccionados',
      'select_all': 'Seleccionar todo',
      'deselect_all': 'Deseleccionar todo',
      'items_selected': 'elementos seleccionados',
    },
    'fr': {
      'settings': 'Paramètres',
      'general': 'Général',
      'app_language': 'Langue de l\'application',
      'time_zone': 'Fuseau horaire',
      'date_format': 'Format de date',
      'appearance': 'Apparence',
      'dark_mode': 'Mode sombre',
      'font_size': 'Taille de police',
      'audio_ai': 'Audio & IA',
      'voice_response': 'Réponse vocale',
      'default_ai_mode': 'Mode IA par défaut',
      'safety': 'Sécurité',
      'emergency_contact': 'Contact d\'urgence',
      'support': 'Support',
      'faq': 'FAQ',
      'contact_support': 'Contacter le support',
      'feedback': 'Commentaires / Signaler un problème',
      'privacy_data': 'Confidentialité & Données',
      'consent_data': 'Consentement & Utilisation des données',
      'delete_account': 'Supprimer le compte',
      'about': 'À propos',
      'terms': 'Conditions générales',
      'privacy_policy': 'Politique de confidentialité',
      'licenses': 'Licences',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'not_set': 'Non défini',
      'home': 'Accueil',
      'reminders': 'Rappels',
      'profile': 'Profil',
      'ai_chat': 'Chat IA',
      'find_doctors': 'Trouver des médecins',
      'analysis': 'Analyse',
      'companion': 'Compagnon',
      'welcome_back': 'Bon retour,',
      'create_avatar': 'Créer un Avatar',
      'manage_avatar': 'Gérer l\'Avatar',
      'reminder_alert': 'Rappel / Alerte',
      'add_reminder': 'Ajouter un rappel',
      'edit_reminder': 'Modifier le rappel',
      'title': 'Titre',
      'description_optional': 'Description (Optionnel)',
      'date': 'Date',
      'time': 'Heure',
      'repeat': 'Répéter',
      'vibration': 'Vibration',
      'vibrate_desc': 'Vibrer lors du déclenchement du rappel',
      'save_reminder': 'ENREGISTRER LE RAPPEL',
      'enter_title': 'Entrez le titre du rappel',
      'enter_desc': 'Entrez la description',
      'today_only': 'Aujourd\'hui seulement',
      'daily': 'Quotidien',
      'weekly': 'Hebdomadaire',
      'monthly': 'Mensuel',
      'err_title': 'Veuillez entrer un titre',
      'err_future': 'Veuillez sélectionner une heure future',
      'msg_updated': 'Rappel mis à jour !',
      'msg_saved': 'Rappel enregistré avec succès !',
      'mental_health_analysis': 'Analyse de Santé Mentale',
      'emotional_overview': 'Aperçu Émotionnel',
      'time_based_analysis': 'Analyse Basée sur le Temps',
      'daily_mood_timeline': 'Chronologie de l\'Humeur Quotidienne',
      'mental_health_score': 'Score de Santé Mentale',
      'no_data': 'Aucune donnée disponible',
      'no_emotional_data': 'Aucune donnée émotionnelle enregistrée pour le moment.',
      'no_timeline_data': 'Aucune donnée de chronologie disponible.',
      'out_of_100': 'sur 100',
      'score_desc': 'Basé sur vos interactions récentes et vos schémas émotionnels.',
      'excellent': 'Excellent',
      'good': 'Bon',
      'fair': 'Passable',
      'needs_attention': 'Nécessite une Attention',
      'positive': 'Positif',
      'negative': 'Négatif',
      'morning': 'Matin',
      'afternoon': 'Après-midi',
      'evening': 'Soir',
      'night': 'Nuit',
      'today': 'Aujourd\'hui',
      'yesterday': 'Hier',
      'last_7_days': '7 derniers jours',
      'last_30_days': '30 derniers jours',
      'this_month': 'Ce mois-ci',
      'last_month': 'Mois dernier',
      'all_time': 'Tout le temps',
      'find_doctors_title': 'Trouver des Médecins',
      'no_doctors': 'Aucun médecin trouvé à proximité.',
      'view': 'Voir',
      'rating': 'Évaluation',
      'yrs': 'Ans',
      'address': 'Adresse',
      'availability': 'Disponibilité',
      'book_appointment': 'PRENDRE RENDEZ-VOUS',
      'yrs_exp': 'ans d\'exp',
      'funny': 'Drôle',
      'search': 'Rechercher',
      'mental_health': 'Santé Mentale',
      'study': 'Étudier',
      'no_history': 'Aucun historique pour ce mode',
      'untitled_chat': 'Chat sans titre',
      'no_msg_share': 'Aucun message à partager',
      'share_chat_as': 'Partager le chat sous',
      'text_format': 'Format texte',
      'pdf_format': 'Format PDF',
      'select_chat_mode': 'Sélectionner le mode de chat',
      'ai_chat_title': 'Chat IA',
      'voice_reply': 'Réponse vocale',
      'select_voice': 'Sélectionner la voix',
      'new_chat': 'Nouveau chat',
      'chat_history': 'Historique du chat',
      'back_to_chat': 'Retour au chat',
      'view_analysis': 'Voir l\'analyse',
      'download_chat': 'Télécharger le chat',
      'share_chat': 'Partager le chat',
      'type_message': 'Tapez un message...',
      'select_mode': 'Sélectionner le mode',
      'stop_listening': 'Arrêter l\'écoute',
      'start_listening': 'Commencer l\'écoute',
      'female': 'Femme',
      'male': 'Homme',
      'no_system_voices': 'Aucune voix système trouvée. Veuillez vérifier les paramètres de votre appareil.',
      'selected_voice_msg': 'Voix sélectionnée : ',
      'preview_failed': 'Échec de l\'aperçu : ',
      'no_voices_available': 'Aucune voix disponible',
      'unknown': 'Inconnu',
      'select': 'Sélectionner',
      'retry': 'Réessayer',
      'hello_voice': 'Bonjour, je suis {name}. Comment puis-je vous aider aujourd\'hui ?',
      'email': 'E-mail',
      'phone': 'Téléphone',
      'dob': 'Date de naissance',
      'user_name': 'Nom d\'utilisateur',
      'edit_profile': 'Modifier le profil',
      'tap_to_change': 'Appuyez pour changer la photo',
      'username': 'Nom d\'utilisateur',
      'phone_number': 'Numéro de téléphone',
      'save_changes': 'ENREGISTRER LES MODIFICATIONS',
      'profile_updated': 'Profil mis à jour avec succès !',
      'failed_update': 'Échec de la mise à jour du profil',
      'enter_username': 'Veuillez entrer le nom d\'utilisateur',
      'enter_email': 'Veuillez entrer l\'e-mail',
      'enter_valid_email': 'Veuillez entrer un e-mail valide',
      'enter_phone': 'Veuillez entrer le numéro de téléphone',
      'select_dob': 'Veuillez sélectionner la date de naissance',
      'relationship': 'Relation',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'delete': 'Supprimer',
      'delete_account_confirm': 'Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est irréversible et toutes vos données seront perdues.',
      'account_deleted': 'Compte supprimé avec succès.',
      'failed_delete_account': 'Échec de la suppression du compte.',
      'app_version': 'Version de l\'application',
      'analysis_dashboard': 'Tableau de bord d\'analyse',
      'insights': 'Aperçus',
      'positive': 'Positif',
      'negative': 'Négatif',
      'mostly_positive_msg': 'Bon travail ! Continuez sur cette lancée positive ! 😊',
      'mostly_negative_msg': 'Un peu difficile ? C\'est normal, continuez ! 💪',
      'emotion_trend': 'Tendance émotionnelle au fil du temps',
      'daily_mood_timeline': 'Chronologie de l\'humeur quotidienne',
      'score': 'Score',
      'excellent': 'Excellent',
      'good': 'Bon',
      'moderate': 'Modéré',
      'needs_attention': 'Nécessite une attention',
      'score_basis': 'Basé sur vos interactions récentes.',
      'no_data': 'Aucune donnée pour cette période',
      'morning': 'Matin',
      'afternoon': 'Après-midi',
      'evening': 'Soir',
      'night': 'Nuit',
      'happy': 'Heureux',
      'sad': 'Triste',
      'angry': 'En colère',
      'calm': 'Calme',
      'no_avatar_selected': 'Aucun avatar sélectionné',
      'default_avatar_msg': 'Salut ! Je suis là pour t\'aider.',
      'select_avatar': 'Sélectionner un avatar',
      'no_avatars_found': 'Aucun avatar trouvé.\nCréez-en un pour commencer !',
      'avatar_set_active': 'Avatar défini comme actif !',
      'avatar_deleted': 'Avatar supprimé avec succès',
      'delete_avatar_confirm': 'Êtes-vous sûr de vouloir supprimer cet avatar ?',
      'create_new_avatar': 'CRÉER UN NOUVEL AVATAR',
      'error_fetching_avatars': 'Erreur lors de la récupération des avatars',
      'error_setting_active_avatar': 'Erreur lors de la définition de l\'avatar actif',
      'error_deleting_avatar': 'Erreur lors de la suppression de l\'avatar',
      'create_your_avatar': 'Créez votre avatar',
      'error_saving_avatar': 'Erreur lors de l\'enregistrement de l\'avatar',
      'close_and_go_home': 'Fermer et aller à l\'accueil',
      'my_new_avatar': 'Mon nouvel avatar',
      'select_ai_mode': 'Sélectionner le mode IA',
      'funny_desc': 'IA avec un sens de l\'humour et des blagues.',
      'search_desc': 'Axé sur la recherche de faits et d\'informations.',
      'mental_health_desc': 'Auditeur empathique et solidaire.',
      'study_desc': 'Aide à l\'apprentissage et aux explications.',
      'snooze': 'Répéter',
      'stop': 'Arrêter',
      'minutes': 'minutes',
      'reminder_msg_prefix': 'Ceci est votre rappel',
      'intelligent_companion': 'Votre compagnon intelligent',
      'mic_access': 'Accès au microphone',
      'mic_desc': 'Nous avons besoin d\'accéder au microphone pour que votre compagnon avatar puisse vous écouter et vous répondre.',
      'notif_access': 'Notifications',
      'notif_desc': 'Activez les notifications pour recevoir des rappels et des alertes importants de votre compagnon.',
      'overlay_access': 'Afficher sur d\'autres applications',
      'overlay_desc': 'Autorisez l\'avatar à apparaître sur d\'autres applications lorsqu\'un rappel se déclenche, même sur l\'écran de verrouillage.',
      'battery_access': 'Optimisation de la batterie',
      'battery_desc': 'Pour garantir que les rappels sonnent à l\'heure, veuillez autoriser l\'application à s\'exécuter en arrière-plan sans restrictions.',
      'alarm_access': 'Alarmes exactes',
      'alarm_desc': 'Pour garantir que vos rappels se déclenchent exactement à l\'heure, veuillez autoriser l\'application à définir des alarmes exactes.',
      'location_access': 'Accès à la localisation',
      'location_desc': 'Facultatif : nous utilisons votre localisation pour vous aider à trouver des médecins et des services à proximité.',
      'allow_access': 'Autoriser l\'accès',
      'skip_for_now': 'Ignorer pour l\'instant',
      'no_thanks': 'Non merci',
      'permission_required': 'Permission requise',
      'permission_desc': 'Cette fonctionnalité nécessite une permission pour fonctionner. Veuillez l\'activer dans les paramètres de l\'application.',
      'permissions_required_reminder': 'Des permissions sont nécessaires pour créer des rappels. Veuillez accorder les permissions nécessaires.',
      'open_settings': 'Ouvrir les paramètres',
      'sign_in_continue': 'Connectez-vous pour continuer',
      'login_failed': 'Échec de la connexion',
      'enter_email': 'Veuillez entrer votre e-mail',
      'enter_valid_email': 'Veuillez entrer un e-mail valide',
      'enter_password': 'Veuillez entrer votre mot de passe',
      'password_min_length': 'Le mot de passe doit comporter au moins 6 caractères',
      'no_account_signup': "Vous n'avez pas de compte ? Inscrivez-vous",
      'login_caps': 'CONNEXION',
      'create_account': 'Créer un compte',
      'join_start_chatting': 'Rejoignez-nous pour commencer à discuter',
      'full_name': 'Nom complet',
      'phone_number': 'Numéro de téléphone',
      'enter_name': 'Veuillez entrer votre nom',
      'enter_phone': 'Veuillez entrer votre numéro de téléphone',
      'enter_valid_phone': 'Veuillez entrer un numéro de téléphone valide à 10 chiffres',
      'select_dob': 'Veuillez sélectionner votre date de naissance',
      'registration_success': 'Inscription réussie !',
      'registration_failed': 'Échec de l\'inscription',
      'already_account_signin': 'Vous avez déjà un compte ? Connectez-vous',
      'register_caps': 'S\'INSCRIRE',
      'avatars': 'Avatars',
      'active': 'Actif',
      'exit': 'Quitter',
      'no_chat_history': 'Aucun historique de chat trouvé.',
      'chat_downloaded_preview': 'Chat téléchargé (Aperçu)',
      'delete_chat': 'Supprimer le chat',
      'delete_chat_confirm': 'Êtes-vous sûr de vouloir supprimer cet historique de chat ?',
      'conversation_deleted': 'Conversation supprimée',
      'no_reminders_set': 'Aucun rappel défini.',
      'repeat_none': 'Répéter : Aucun',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'reminder_deleted': 'Rappel supprimé',
      'chat': 'Chat',
      'searching': 'Recherche',
      'this_week': 'Cette semaine',
      'last_week': 'La semaine dernière',
      'you': 'Vous',
      'ai': 'IA',
      'chat_conversation_subject': 'Ma conversation de chat IA',
      'chat_conversation_header': 'Conversation de chat IA',
      'notifications': 'Notifications',
      'no_notifications': 'Pas de nouvelles notifications',
      'delete_selected': 'Supprimer la sélection',
      'select_all': 'Tout sélectionner',
      'deselect_all': 'Tout désélectionner',
      'items_selected': 'éléments sélectionnés',
    },
    'hi': {
      'settings': 'सेटिंग्स',
      'general': 'सामान्य',
      'app_language': 'ऐप की भाषा',
      'time_zone': 'समय क्षेत्र',
      'date_format': 'तारीख का प्रारूप',
      'appearance': 'दिखावट',
      'dark_mode': 'डार्क मोड',
      'font_size': 'फ़ॉन्ट आकार',
      'audio_ai': 'ऑडियो और एआई',
      'voice_response': 'आवाज प्रतिक्रिया',
      'default_ai_mode': 'डिफ़ॉल्ट एआई मोड',
      'safety': 'सुरक्षा',
      'emergency_contact': 'आपातकालीन संपर्क',
      'support': 'सहायता',
      'faq': 'सामान्य प्रश्न',
      'contact_support': 'सहायता से संपर्क करें',
      'feedback': 'प्रतिक्रिया / समस्या की रिपोर्ट करें',
      'privacy_data': 'गोपनीयता और डेटा',
      'consent_data': 'सहमति और डेटा उपयोग',
      'delete_account': 'खाता हटाएं',
      'about': 'के बारे में',
      'terms': 'नियम और शर्तें',
      'privacy_policy': 'गोपनीयता नीति',
      'licenses': 'लाइसेंस',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'not_set': 'सेट नहीं है',
      'home': 'होम',
      'reminders': 'अनुस्मारक',
      'profile': 'प्रोफ़ाइल',
      'ai_chat': 'एआई चैट',
      'find_doctors': 'डॉक्टर खोजें',
      'analysis': 'विश्लेषण',
      'companion': 'साथी',
      'welcome_back': 'वापसी पर स्वागत है,',
      'create_avatar': 'अवतार बनाएं',
      'manage_avatar': 'अवतार प्रबंधित करें',
      'reminder_alert': 'अनुस्मारक / अलर्ट',
      'add_reminder': 'अनुस्मारक जोड़ें',
      'edit_reminder': 'अनुस्मारक संपादित करें',
      'title': 'शीर्षक',
      'description_optional': 'विवरण (वैकल्पिक)',
      'date': 'तारीख',
      'time': 'समय',
      'repeat': 'दोहराएं',
      'vibration': 'कंपन',
      'vibrate_desc': 'अनुस्मारक ट्रिगर होने पर कंपन करें',
      'save_reminder': 'अनुस्मारक सहेजें',
      'enter_title': 'अनुस्मारक शीर्षक दर्ज करें',
      'enter_desc': 'विवरण दर्ज करें',
      'today_only': 'केवल आज',
      'daily': 'दैनिक',
      'weekly': 'साप्ताहिक',
      'monthly': 'मासिक',
      'err_title': 'कृपया एक शीर्षक दर्ज करें',
      'err_future': 'कृपया भविष्य का समय चुनें',
      'msg_updated': 'अनुस्मारक अपडेट किया गया!',
      'msg_saved': 'अनुस्मारक सफलतापूर्वक सहेजा गया!',
      'mental_health_analysis': 'मानसिक स्वास्थ्य विश्लेषण',
      'emotional_overview': 'भावनात्मक अवलोकन',
      'time_based_analysis': 'समय-आधारित विश्लेषण',
      'daily_mood_timeline': 'दैनिक मनोदशा समयरेखा',
      'mental_health_score': 'मानसिक स्वास्थ्य स्कोर',
      'no_data': 'कोई डेटा उपलब्ध नहीं है',
      'no_emotional_data': 'अभी तक कोई भावनात्मक डेटा रिकॉर्ड नहीं किया गया है।',
      'no_timeline_data': 'कोई समयरेखा डेटा उपलब्ध नहीं है।',
      'out_of_100': '100 में से',
      'score_desc': 'आपके हालिया इंटरैक्शन और भावनात्मक पैटर्न के आधार पर।',
      'excellent': 'उत्कृष्ट',
      'good': 'अच्छा',
      'fair': 'ठीक',
      'needs_attention': 'ध्यान देने की आवश्यकता है',
      'positive': 'सकारात्मक',
      'negative': 'नकारात्मक',
      'morning': 'सुबह',
      'afternoon': 'दोपहर',
      'evening': 'शाम',
      'night': 'रात',
      'today': 'आज',
      'yesterday': 'कल',
      'last_7_days': 'पिछले 7 दिन',
      'last_30_days': 'पिछले 30 दिन',
      'this_month': 'इस महीने',
      'last_month': 'पिछले महीने',
      'all_time': 'कुल समय',
      'find_doctors_title': 'डॉक्टर खोजें',
      'no_doctors': 'आस-पास कोई डॉक्टर नहीं मिला।',
      'view': 'देखें',
      'rating': 'रेटिंग',
      'yrs': 'वर्ष',
      'address': 'पता',
      'availability': 'उपलब्धता',
      'book_appointment': 'अपॉइंटमेंट बुक करें',
      'yrs_exp': 'वर्षों का अनुभव',
      'funny': 'मजेदार',
      'search': 'खोजें',
      'mental_health': 'मानसिक स्वास्थ्य',
      'study': 'अध्ययन',
      'no_history': 'इस मोड के लिए कोई इतिहास नहीं है',
      'untitled_chat': 'बिना शीर्षक वाला चैट',
      'no_msg_share': 'साझा करने के लिए कोई संदेश नहीं है',
      'share_chat_as': 'चैट साझा करें',
      'text_format': 'टेक्स्ट प्रारूप',
      'pdf_format': 'पीडीएफ प्रारूप',
      'select_chat_mode': 'चैट मोड चुनें',
      'ai_chat_title': 'एआई चैट',
      'voice_reply': 'आवाज प्रतिक्रिया',
      'select_voice': 'आवाज चुनें',
      'new_chat': 'नई चैट',
      'chat_history': 'चैट इतिहास',
      'back_to_chat': 'चैट पर वापस जाएं',
      'view_analysis': 'विश्लेषण देखें',
      'download_chat': 'चैट डाउनलोड करें',
      'share_chat': 'चैट साझा करें',
      'type_message': 'एक संदेश टाइप करें...',
      'select_mode': 'मोड चुनें',
      'stop_listening': 'सुनना बंद करें',
      'start_listening': 'सुनना शुरू करें',
      'female': 'महिला',
      'male': 'पुरुष',
      'no_system_voices': 'कोई सिस्टम आवाज़ नहीं मिली। कृपया अपने डिवाइस की सेटिंग्स जांचें।',
      'selected_voice_msg': 'चुनी गई आवाज़: ',
      'preview_failed': 'पूर्वावलोकन विफल रहा: ',
      'no_voices_available': 'कोई आवाज़ उपलब्ध नहीं है',
      'unknown': 'अज्ञात',
      'select': 'चुनें',
      'retry': 'पुनः प्रयास करें',
      'hello_voice': 'नमस्ते, मैं {name} हूँ। मैं आज आपकी कैसे मदद कर सकता हूँ?',
      'email': 'ईमेल',
      'phone': 'फ़ोन',
      'dob': 'जन्म तिथि',
      'user_name': 'उपयोगकर्ता का नाम',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'tap_to_change': 'फोटो बदलने के लिए टैप करें',
      'username': 'उपयोगकर्ता नाम',
      'phone_number': 'फ़ोन नंबर',
      'save_changes': 'परिवर्तन सहेजें',
      'profile_updated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
      'failed_update': 'प्रोफ़ाइल अपडेट करने में विफल',
      'enter_username': 'कृपया उपयोगकर्ता नाम दर्ज करें',
      'enter_email': 'कृपया ईमेल दर्ज करें',
      'enter_valid_email': 'कृपया एक मान्य ईमेल दर्ज करें',
      'enter_phone': 'कृपया फ़ोन नंबर दर्ज करें',
      'select_dob': 'कृपया जन्म तिथि चुनें',
      'relationship': 'संबंध',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'delete': 'हटाएं',
      'delete_account_confirm': 'क्या आप वाकई अपना खाता हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती और आपका सारा डेटा खो जाएगा।',
      'account_deleted': 'खाता सफलतापूर्वक हटा दिया गया।',
      'failed_delete_account': 'खाता हटाने में विफल।',
      'app_version': 'ऐप संस्करण',
      'analysis_dashboard': 'विश्लेषण डैशबोर्ड',
      'insights': 'अंतर्दृष्टि',
      'positive': 'सकारात्मक',
      'negative': 'नकारात्मक',
      'mostly_positive_msg': 'बहुत अच्छा! सकारात्मक वाइब्स बनाए रखें! 😊',
      'mostly_negative_msg': 'थोड़ा चुनौतीपूर्ण? कोई बात नहीं, आगे बढ़ते रहें! 💪',
      'emotion_trend': 'समय के साथ भावना का रुझान',
      'daily_mood_timeline': 'दैनिक मनोदशा समयरेखा',
      'score': 'स्कोर',
      'excellent': 'उत्कृष्ट',
      'good': 'अच्छा',
      'moderate': 'मध्यम',
      'needs_attention': 'ध्यान देने की आवश्यकता है',
      'score_basis': 'आपकी हालिया बातचीत के आधार पर।',
      'no_data': 'इस अवधि के लिए कोई डेटा नहीं है',
      'morning': 'सुबह',
      'afternoon': 'दोपहर',
      'evening': 'शाम',
      'night': 'रात',
      'happy': 'खुश',
      'sad': 'दुखी',
      'angry': 'गुस्सा',
      'calm': 'शांत',
      'no_avatar_selected': 'कोई अवतार नहीं चुना गया',
      'default_avatar_msg': 'नमस्ते! मैं यहाँ आपकी मदद के लिए हूँ।',
      'select_avatar': 'अवतार चुनें',
      'no_avatars_found': 'कोई अवतार नहीं मिला।\nशुरू करने के लिए एक बनाएं!',
      'avatar_set_active': 'अवतार सक्रिय के रूप में सेट किया गया!',
      'avatar_deleted': 'अवतार सफलतापूर्वक हटा दिया गया',
      'delete_avatar_confirm': 'क्या आप वाकई इस अवतार को हटाना चाहते हैं?',
      'create_new_avatar': 'नया अवतार बनाएं',
      'error_fetching_avatars': 'अवतार प्राप्त करने में त्रुटि',
      'error_setting_active_avatar': 'सक्रिय अवतार सेट करने में त्रुटि',
      'error_deleting_avatar': 'अवतार हटाने में त्रुटि',
      'create_your_avatar': 'अपना अवतार बनाएं',
      'error_saving_avatar': 'अवतार सहेजने में त्रुटि',
      'close_and_go_home': 'बंद करें और होम पर जाएं',
      'my_new_avatar': 'मेरा नया अवतार',
      'select_ai_mode': 'एआई मोड चुनें',
      'funny_desc': 'हास्य और चुटकुलों के साथ एआई।',
      'search_desc': 'तथ्यों और जानकारी को खोजने पर केंद्रित।',
      'mental_health_desc': 'सहानुभूतिपूर्ण और सहायक श्रोता।',
      'study_desc': 'सीखने और स्पष्टीकरण में मदद करता है।',
      'snooze': 'स्नूज़',
      'stop': 'रोकें',
      'minutes': 'मिनट',
      'reminder_msg_prefix': 'यह आपका रिमाइंडर है',
      'intelligent_companion': 'आपका बुद्धिमान साथी',
      'mic_access': 'माइक्रोफ़ोन एक्सेस',
      'mic_desc': 'हमें माइक्रोफ़ोन एक्सेस की आवश्यकता है ताकि आपका अवतार साथी आपकी बात सुन सके और आपको जवाब दे सके।',
      'notif_access': 'सूचनाएं',
      'notif_desc': 'अपने साथी से महत्वपूर्ण रिमाइंडर और अलर्ट प्राप्त करने के लिए सूचनाएं सक्षम करें।',
      'overlay_access': 'अन्य ऐप्स के ऊपर प्रदर्शित करें',
      'overlay_desc': 'रिमाइंडर ट्रिगर होने पर अवतार को अन्य ऐप्स के ऊपर दिखाई देने दें, यहां तक कि लॉक स्क्रीन पर भी।',
      'battery_access': 'बैटरी अनुकूलन',
      'battery_desc': 'यह सुनिश्चित करने के लिए कि रिमाइंडर समय पर बजें, कृपया ऐप को बिना किसी प्रतिबंध के बैकग्राउंड में चलने दें।',
      'alarm_access': 'सटीक अलार्म',
      'alarm_desc': 'यह सुनिश्चित करने के लिए कि आपके रिमाइंडर बिल्कुल समय पर ट्रिगर हों, कृपया ऐप को सटीक अलार्म सेट करने की अनुमति दें।',
      'location_access': 'स्थान एक्सेस',
      'location_desc': 'वैकल्पिक: हम आपके स्थान का उपयोग आपके आस-पास के डॉक्टरों और सेवाओं को खोजने में मदद करने के लिए करते हैं।',
      'allow_access': 'पहुंच की अनुमति दें',
      'skip_for_now': 'अभी के लिए छोड़ें',
      'no_thanks': 'नहीं धन्यवाद',
      'permission_required': 'अनुमति आवश्यक',
      'permission_desc': 'इस सुविधा को कार्य करने के लिए अनुमति की आवश्यकता है। कृपया इसे ऐप सेटिंग्स में सक्षम करें।',
      'open_settings': 'सेटिंग्स खोलें',
      'sign_in_continue': 'जारी रखने के लिए साइन इन करें',
      'login_failed': 'लॉगिन विफल',
      'enter_email': 'कृपया ईमेल दर्ज करें',
      'enter_valid_email': 'कृपया एक वैध ईमेल दर्ज करें',
      'enter_password': 'कृपया पासवर्ड दर्ज करें',
      'password_min_length': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए',
      'no_account_signup': "खाता नहीं है? साइन अप करें",
      'login_caps': 'लॉगिन',
      'create_account': 'खाता बनाएं',
      'join_start_chatting': 'चैटिंग शुरू करने के लिए हमसे जुड़ें',
      'full_name': 'पूरा नाम',
      'phone_number': 'फ़ोन नंबर',
      'enter_name': 'कृपया अपना नाम दर्ज करें',
      'enter_phone': 'कृपया फ़ोन नंबर दर्ज करें',
      'enter_valid_phone': 'कृपया एक वैध 10-अंकीय फ़ोन नंबर दर्ज करें',
      'select_dob': 'कृपया अपनी जन्मतिथि चुनें',
      'registration_success': 'पंजीकरण सफल!',
      'registration_failed': 'पंजीकरण विफल',
      'already_account_signin': 'पहले से ही एक खाता है? साइन इन करें',
      'register_caps': 'रजिस्टर',
      'avatars': 'अवतार',
      'active': 'सक्रिय',
      'exit': 'बाहर निकलें',
      'no_chat_history': 'कोई चैट इतिहास नहीं मिला।',
      'chat_downloaded_preview': 'चैट डाउनलोड किया गया (पूर्वावलोकन)',
      'delete_chat': 'चैट हटाएं',
      'delete_chat_confirm': 'क्या आप वाकई इस चैट इतिहास को हटाना चाहते हैं?',
      'conversation_deleted': 'बातचीत हटा दी गई',
      'no_reminders_set': 'कोई रिमाइंडर सेट नहीं है।',
      'repeat_none': 'दोहराएं: कोई नहीं',
      'edit': 'संपादित करें',
      'delete': 'हटाएं',
      'reminder_deleted': 'रिमाइंडर हटा दिया गया',
      'chat': 'चैट',
      'searching': 'खोज रहे हैं',
      'this_week': 'इस सप्ताह',
      'last_week': 'पिछले सप्ताह',
      'you': 'आप',
      'ai': 'एआई',
      'chat_conversation_subject': 'मेरी एआई चैट बातचीत',
      'chat_conversation_header': 'एआई चैट बातचीत',
      'notifications': 'सूचनाएं',
      'no_notifications': 'कोई नई सूचना नहीं',
      'delete_selected': 'चयनित हटाएं',
      'select_all': 'सभी चुनें',
      'deselect_all': 'सभी अचयनित करें',
      'items_selected': 'आइटम चयनित',
    },
    'de': {
      'settings': 'Einstellungen',
      'general': 'Allgemein',
      'app_language': 'App-Sprache',
      'time_zone': 'Zeitzone',
      'date_format': 'Datumsformat',
      'appearance': 'Aussehen',
      'dark_mode': 'Dunkelmodus',
      'font_size': 'Schriftgröße',
      'audio_ai': 'Audio & KI',
      'voice_response': 'Sprachantwort',
      'default_ai_mode': 'Standard-KI-Modus',
      'safety': 'Sicherheit',
      'emergency_contact': 'Notfallkontakt',
      'support': 'Support',
      'faq': 'FAQ',
      'contact_support': 'Support kontaktieren',
      'feedback': 'Feedback / Problem melden',
      'privacy_data': 'Datenschutz & Daten',
      'consent_data': 'Einwilligung & Datennutzung',
      'delete_account': 'Konto löschen',
      'about': 'Über',
      'terms': 'AGB',
      'privacy_policy': 'Datenschutzerklärung',
      'licenses': 'Lizenzen',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'not_set': 'Nicht festgelegt',
      'home': 'Startseite',
      'reminders': 'Erinnerungen',
      'profile': 'Profil',
      'ai_chat': 'KI-Chat',
      'find_doctors': 'Ärzte finden',
      'analysis': 'Analyse',
      'companion': 'Begleiter',
      'welcome_back': 'Willkommen zurück,',
      'create_avatar': 'Avatar erstellen',
      'manage_avatar': 'Avatar verwalten',
      'reminder_alert': 'Erinnerung / Alarm',
      'add_reminder': 'Erinnerung hinzufügen',
      'edit_reminder': 'Erinnerung bearbeiten',
      'title': 'Titel',
      'description_optional': 'Beschreibung (Optional)',
      'date': 'Datum',
      'time': 'Uhrzeit',
      'repeat': 'Wiederholen',
      'vibration': 'Vibration',
      'vibrate_desc': 'Vibrieren, wenn die Erinnerung ausgelöst wird',
      'save_reminder': 'ERINNERUNG SPEICHERN',
      'enter_title': 'Titel der Erinnerung eingeben',
      'enter_desc': 'Beschreibung eingeben',
      'today_only': 'Nur heute',
      'daily': 'Täglich',
      'weekly': 'Wöchentlich',
      'monthly': 'Monatlich',
      'err_title': 'Bitte geben Sie einen Titel ein',
      'err_future': 'Bitte wählen Sie eine Zeit in der Zukunft',
      'msg_updated': 'Erinnerung aktualisiert!',
      'msg_saved': 'Erinnerung erfolgreich gespeichert!',
      'mental_health_analysis': 'Analyse der mentalen Gesundheit',
      'emotional_overview': 'Emotionaler Überblick',
      'time_based_analysis': 'Zeitbasierte Analyse',
      'daily_mood_timeline': 'Tägliche Stimmungshistorie',
      'mental_health_score': 'Mentaler Gesundheitswert',
      'no_data': 'Keine Daten verfügbar',
      'no_emotional_data': 'Noch keine emotionalen Daten aufgezeichnet.',
      'no_timeline_data': 'Keine Historien-Daten verfügbar.',
      'out_of_100': 'von 100',
      'score_desc': 'Basierend auf Ihren letzten Interaktionen und emotionalen Mustern.',
      'excellent': 'Ausgezeichnet',
      'good': 'Gut',
      'fair': 'Akzeptabel',
      'needs_attention': 'Benötigt Aufmerksamkeit',
      'positive': 'Positiv',
      'negative': 'Negativ',
      'morning': 'Morgen',
      'afternoon': 'Nachmittag',
      'evening': 'Abend',
      'night': 'Nacht',
      'today': 'Heute',
      'yesterday': 'Gestern',
      'last_7_days': 'Letzte 7 Tage',
      'last_30_days': 'Letzte 30 Tage',
      'this_month': 'Diesen Monat',
      'last_month': 'Letzten Monat',
      'all_time': 'Gesamte Zeit',
      'find_doctors_title': 'Ärzte finden',
      'no_doctors': 'Keine Ärzte in der Nähe gefunden.',
      'view': 'Ansehen',
      'rating': 'Bewertung',
      'yrs': 'Jahre',
      'address': 'Adresse',
      'availability': 'Verfügbarkeit',
      'book_appointment': 'TERMIN BUCHEN',
      'yrs_exp': 'Jahre Erf.',
      'funny': 'Lustig',
      'search': 'Suchen',
      'mental_health': 'Mentale Gesundheit',
      'study': 'Lernen',
      'no_history': 'Kein Verlauf für diesen Modus',
      'untitled_chat': 'Unbenannter Chat',
      'no_msg_share': 'Keine Nachrichten zum Teilen',
      'share_chat_as': 'Chat teilen als',
      'text_format': 'Textformat',
      'pdf_format': 'PDF-Format',
      'select_chat_mode': 'Chat-Modus auswählen',
      'ai_chat_title': 'KI-Chat',
      'voice_reply': 'Sprachantwort',
      'select_voice': 'Stimme auswählen',
      'new_chat': 'Neuer Chat',
      'chat_history': 'Chat-Verlauf',
      'back_to_chat': 'Zurück zum Chat',
      'view_analysis': 'Analyse anzeigen',
      'download_chat': 'Chat herunterladen',
      'share_chat': 'Chat teilen',
      'type_message': 'Nachricht eingeben...',
      'select_mode': 'Modus auswählen',
      'stop_listening': 'Zuhören beenden',
      'start_listening': 'Zuhören starten',
      'female': 'Weiblich',
      'male': 'Männlich',
      'no_system_voices': 'Keine Systemstimmen gefunden. Bitte überprüfen Sie Ihre Geräteeinstellungen.',
      'selected_voice_msg': 'Ausgewählte Stimme: ',
      'preview_failed': 'Vorschau fehlgeschlagen: ',
      'no_voices_available': 'Keine Stimmen verfügbar',
      'unknown': 'Unbekannt',
      'select': 'Auswählen',
      'retry': 'Wiederholen',
      'hello_voice': 'Hallo, ich bin {name}. Wie kann ich dir heute helfen?',
      'email': 'E-Mail',
      'phone': 'Telefon',
      'dob': 'Geburtsdatum',
      'user_name': 'Benutzername',
      'edit_profile': 'Profil bearbeiten',
      'tap_to_change': 'Tippen, um das Foto zu ändern',
      'username': 'Benutzername',
      'phone_number': 'Telefonnummer',
      'save_changes': 'ÄNDERUNGEN SPEICHERN',
      'profile_updated': 'Profil erfolgreich aktualisiert!',
      'failed_update': 'Profilaktualisierung fehlgeschlagen',
      'enter_username': 'Bitte Benutzernamen eingeben',
      'enter_email': 'Bitte E-Mail eingeben',
      'enter_valid_email': 'Bitte eine gültige E-Mail eingeben',
      'enter_phone': 'Bitte Telefonnummer eingeben',
      'select_dob': 'Bitte Geburtsdatum auswählen',
      'relationship': 'Beziehung',
      'cancel': 'Abbrechen',
      'save': 'Speichern',
      'delete': 'Löschen',
      'delete_account_confirm': 'Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden und alle Ihre Daten gehen verloren.',
      'account_deleted': 'Konto erfolgreich gelöscht.',
      'failed_delete_account': 'Konto konnte nicht gelöscht werden.',
      'app_version': 'App-Version',
      'analysis_dashboard': 'Analyse-Dashboard',
      'insights': 'Einblicke',
      'positive': 'Positiv',
      'negative': 'Negativ',
      'mostly_positive_msg': 'Gute Arbeit! Mach weiter so mit den positiven Vibes! 😊',
      'mostly_negative_msg': 'Ein bisschen herausfordernd? Das ist okay, mach weiter! 💪',
      'emotion_trend': 'Emotionstrend im Zeitverlauf',
      'daily_mood_timeline': 'Tägliche Stimmungschronik',
      'score': 'Punktzahl',
      'excellent': 'Ausgezeichnet',
      'good': 'Gut',
      'moderate': 'Mäßig',
      'needs_attention': 'Benötigt Aufmerksamkeit',
      'score_basis': 'Basierend auf Ihren letzten Interaktionen.',
      'no_data': 'Keine Daten für diesen Zeitraum',
      'morning': 'Morgen',
      'afternoon': 'Nachmittag',
      'evening': 'Abend',
      'night': 'Nacht',
      'happy': 'Glücklich',
      'sad': 'Traurig',
      'angry': 'Wütend',
      'calm': 'Ruhig',
      'no_avatar_selected': 'Kein Avatar ausgewählt',
      'default_avatar_msg': 'Hallo! Ich bin hier, um zu helfen.',
      'select_avatar': 'Avatar auswählen',
      'no_avatars_found': 'Keine Avatare gefunden.\nErstelle einen, um loszulegen!',
      'avatar_set_active': 'Avatar als aktiv gesetzt!',
      'avatar_deleted': 'Avatar erfolgreich gelöscht',
      'delete_avatar_confirm': 'Sind Sie sicher, dass Sie diesen Avatar löschen möchten?',
      'create_new_avatar': 'NEUEN AVATAR ERSTELLEN',
      'error_fetching_avatars': 'Fehler beim Abrufen der Avatare',
      'error_setting_active_avatar': 'Fehler beim Festlegen des aktiven Avatars',
      'error_deleting_avatar': 'Fehler beim Löschen des Avatars',
      'create_your_avatar': 'Erstelle deinen Avatar',
      'error_saving_avatar': 'Fehler beim Speichern des Avatars',
      'close_and_go_home': 'Schließen und zum Home gehen',
      'my_new_avatar': 'Mein neuer Avatar',
      'select_ai_mode': 'KI-Modus auswählen',
      'funny_desc': 'KI mit Sinn für Humor und Witzen.',
      'search_desc': 'Konzentriert auf das Finden von Fakten und Infos.',
      'mental_health_desc': 'Empathischer und unterstützender Zuhörer.',
      'study_desc': 'Hilft beim Lernen und Erklären.',
      'snooze': 'Schlummern',
      'stop': 'Stopp',
      'minutes': 'Minuten',
      'reminder_msg_prefix': 'Dies ist Ihre Erinnerung',
      'intelligent_companion': 'Ihr intelligenter Begleiter',
      'mic_access': 'Mikrofonzugriff',
      'mic_desc': 'Wir benötigen Mikrofonzugriff, damit Ihr Avatar-Begleiter Ihnen zuhören und antworten kann.',
      'notif_access': 'Benachrichtigungen',
      'notif_desc': 'Aktivieren Sie Benachrichtigungen, um wichtige Erinnerungen und Warnungen von Ihrem Begleiter zu erhalten.',
      'overlay_access': 'Über anderen Apps anzeigen',
      'overlay_desc': 'Erlauben Sie dem Avatar, über anderen Apps zu erscheinen, wenn eine Erinnerung ausgelöst wird, auch auf dem Sperrbildschirm.',
      'battery_access': 'Akku-Optimierung',
      'battery_desc': 'Um sicherzustellen, dass Erinnerungen rechtzeitig klingeln, erlauben Sie der App bitte, ohne Einschränkungen im Hintergrund zu laufen.',
      'alarm_access': 'Genaue Alarme',
      'alarm_desc': 'Um sicherzustellen, dass Ihre Erinnerungen genau zum richtigen Zeitpunkt ausgelöst werden, erlauben Sie der App bitte, genaue Alarme einzustellen.',
      'location_access': 'Standortzugriff',
      'location_desc': 'Optional: Wir verwenden Ihren Standort, um Ihnen zu helfen, Ärzte und Dienste in der Nähe zu finden.',
      'allow_access': 'Zugriff erlauben',
      'skip_for_now': 'Vorerst überspringen',
      'no_thanks': 'Nein danke',
      'permission_required': 'Berechtigung erforderlich',
      'permission_desc': 'Diese Funktion erfordert eine Berechtigung, um zu funktionieren. Bitte aktivieren Sie diese in den App-Einstellungen.',
      'open_settings': 'Einstellungen öffnen',
      'sign_in_continue': 'Melden Sie sich an, um fortzufahren',
      'login_failed': 'Login fehlgeschlagen',
      'enter_email': 'Bitte E-Mail eingeben',
      'enter_valid_email': 'Bitte eine gültige E-Mail eingeben',
      'enter_password': 'Bitte Passwort eingeben',
      'password_min_length': 'Das Passwort muss mindestens 6 Zeichen lang sein',
      'no_account_signup': "Sie haben noch kein Konto? Registrieren",
      'login_caps': 'ANMELDEN',
      'create_account': 'Konto erstellen',
      'join_start_chatting': 'Treten Sie uns bei, um zu chatten',
      'full_name': 'Vollständiger Name',
      'phone_number': 'Telefonnummer',
      'enter_name': 'Bitte Namen eingeben',
      'enter_phone': 'Bitte Telefonnummer eingeben',
      'enter_valid_phone': 'Bitte eine gültige 10-stellige Telefonnummer eingeben',
      'select_dob': 'Bitte Geburtsdatum auswählen',
      'registration_success': 'Registrierung erfolgreich!',
      'registration_failed': 'Registrierung fehlgeschlagen',
      'already_account_signin': 'Haben Sie bereits ein Konto? Anmelden',
      'register_caps': 'REGISTRIEREN',
      'avatars': 'Avatare',
      'active': 'Aktiv',
      'exit': 'Beenden',
      'no_chat_history': 'Kein Chat-Verlauf gefunden.',
      'chat_downloaded_preview': 'Chat heruntergeladen (Vorschau)',
      'delete_chat': 'Chat löschen',
      'delete_chat_confirm': 'Sind Sie sicher, dass Sie diesen Chat-Verlauf löschen möchten?',
      'conversation_deleted': 'Gespräch gelöscht',
      'no_reminders_set': 'Keine Erinnerungen eingestellt.',
      'repeat_none': 'Wiederholen: Keine',
      'edit': 'Bearbeiten',
      'delete': 'Löschen',
      'reminder_deleted': 'Erinnerung gelöscht',
      'chat': 'Chat',
      'searching': 'Suchen',
      'this_week': 'Diese Woche',
      'last_week': 'Letzte Woche',
      'you': 'Du',
      'ai': 'KI',
      'chat_conversation_subject': 'Meine KI-Chat-Konversation',
      'chat_conversation_header': 'KI-Chat-Konversation',
      'notifications': 'Benachrichtigungen',
      'no_notifications': 'Keine neuen Benachrichtigungen',
      'delete_selected': 'Ausgewählte löschen',
      'select_all': 'Alle auswählen',
      'deselect_all': 'Alle abwählen',
      'items_selected': 'Elemente ausgewählt',
    },
    'ta': {
      'settings': 'அமைப்புகள்',
      'general': 'பொதுவானவை',
      'app_language': 'பயன்பாட்டு மொழி',
      'time_zone': 'நேர மண்டலம்',
      'date_format': 'தேதி வடிவம்',
      'appearance': 'தோற்றம்',
      'dark_mode': 'இருண்ட பயன்முறை',
      'font_size': 'எழுத்து அளவு',
      'audio_ai': 'ஆடியோ & AI',
      'voice_response': 'குரல் பதில்',
      'default_ai_mode': 'இயல்புநிலை AI பயன்முறை',
      'safety': 'பாதுகாப்பு',
      'emergency_contact': 'அவசர தொடர்பு',
      'support': 'ஆதரவு',
      'faq': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
      'contact_support': 'ஆதரவைத் தொடர்பு கொள்ளவும்',
      'feedback': 'கருத்து / சிக்கலைப் புகாரளிக்கவும்',
      'privacy_data': 'தனியுரிமை & தரவு',
      'consent_data': 'ஒப்புதல் & தரவு பயன்பாடு',
      'delete_account': 'கணக்கை நீக்கு',
      'about': 'பற்றி',
      'terms': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
      'privacy_policy': 'தனியுரிமைக் கொள்கை',
      'licenses': 'உரிமங்கள்',
      'save': 'சேமி',
      'cancel': 'ரத்துசெய்',
      'not_set': 'அமைக்கப்படவில்லை',
      'home': 'முகப்பு',
      'reminders': 'நினைவூட்டல்கள்',
      'profile': 'சுயவிவரம்',
      'ai_chat': 'AI அரட்டை',
      'find_doctors': 'மருத்துவர்களைக் கண்டறியவும்',
      'analysis': 'பகுப்பாய்வு',
      'companion': 'துணை',
      'welcome_back': 'மீண்டும் வருக,',
      'create_avatar': 'அவதாரத்தை உருவாக்கு',
      'manage_avatar': 'அவதாரத்தை நிர்வகி',
      'reminder_alert': 'நினைவூட்டல் / எச்சரிக்கை',
      'add_reminder': 'நினைவூட்டலைச் சேர்',
      'edit_reminder': 'நினைவூட்டலைத் திருத்து',
      'title': 'தலைப்பு',
      'description_optional': 'விளக்கம் (விருப்பமானது)',
      'date': 'தேதி',
      'time': 'நேரம்',
      'repeat': 'மீண்டும் செய்',
      'vibration': 'அதிர்வு',
      'vibrate_desc': 'நினைவூட்டல் தூண்டப்படும்போது அதிர்வுறும்',
      'save_reminder': 'நினைவூட்டலைச் சேமி',
      'enter_title': 'நினைவூட்டல் தலைப்பை உள்ளிடவும்',
      'enter_desc': 'விளக்கத்தை உள்ளிடவும்',
      'today_only': 'இன்று மட்டும்',
      'daily': 'தினசரி',
      'weekly': 'வாராந்திரம்',
      'monthly': 'மாதாந்திரம்',
      'err_title': 'தயவுசெய்து ஒரு தலைப்பை உள்ளிடவும்',
      'err_future': 'தயவுசெய்து எதிர்கால நேரத்தைத் தேர்ந்தெடுக்கவும்',
      'msg_updated': 'நினைவூட்டல் புதுப்பிக்கப்பட்டது!',
      'msg_saved': 'நினைவூட்டல் வெற்றிகரமாக சேமிக்கப்பட்டது!',
      'mental_health_analysis': 'மனநல பகுப்பாய்வு',
      'emotional_overview': 'உணர்ச்சி மேலோட்டம்',
      'time_based_analysis': 'நேரம் சார்ந்த பகுப்பாய்வு',
      'daily_mood_timeline': 'தினசரி மனநிலை காலவரிசை',
      'mental_health_score': 'மனநல மதிப்பெண்',
      'no_data': 'தரவு எதுவும் கிடைக்கவில்லை',
      'no_emotional_data': 'உணர்ச்சித் தரவு இன்னும் பதிவு செய்யப்படவில்லை.',
      'no_timeline_data': 'காலவரிசைத் தரவு எதுவும் கிடைக்கவில்லை.',
      'out_of_100': '100-க்கு',
      'score_desc': 'உங்கள் சமீபத்திய தொடர்புகள் மற்றும் உணர்ச்சி வடிவங்களின் அடிப்படையில்.',
      'excellent': 'சிறப்பானது',
      'good': 'நல்லது',
      'fair': 'பரவாயில்லை',
      'needs_attention': 'கவனம் தேவை',
      'positive': 'நேர்மறை',
      'negative': 'எதிர்மறை',
      'morning': 'காலை',
      'afternoon': 'மதியம்',
      'evening': 'மாலை',
      'night': 'இரவு',
      'today': 'இன்று',
      'yesterday': 'நேற்று',
      'last_7_days': 'கடந்த 7 நாட்கள்',
      'last_30_days': 'கடந்த 30 நாட்கள்',
      'this_month': 'இந்த மாதம்',
      'last_month': 'கடந்த மாதம்',
      'all_time': 'எல்லா நேரமும்',
      'find_doctors_title': 'மருத்துவர்களைக் கண்டறியவும்',
      'no_doctors': 'அருகில் மருத்துவர்கள் யாரும் காணப்படவில்லை.',
      'view': 'பார்',
      'rating': 'மதிப்பீடு',
      'yrs': 'ஆண்டுகள்',
      'address': 'முகவரி',
      'availability': 'கிடைக்கும் தன்மை',
      'book_appointment': 'முன்பதிவு செய்யுங்கள்',
      'yrs_exp': 'ஆண்டுகள் அனுபவம்',
      'funny': 'வேடிக்கை',
      'search': 'தேடல்',
      'mental_health': 'மனநலம்',
      'study': 'படிப்பு',
      'no_history': 'இந்த பயன்முறைக்கு வரலாறு இல்லை',
      'untitled_chat': 'தலைப்பில்லாத அரட்டை',
      'no_msg_share': 'பகிர்வதற்கு செய்திகள் இல்லை',
      'share_chat_as': 'அரட்டையைப் பகிரவும்',
      'text_format': 'உரை வடிவம்',
      'pdf_format': 'PDF வடிவம்',
      'select_chat_mode': 'அரட்டை பயன்முறையைத் தேர்ந்தெடுக்கவும்',
      'ai_chat_title': 'AI அரட்டை',
      'voice_reply': 'குரல் பதில்',
      'select_voice': 'குரலைத் தேர்ந்தெடுக்கவும்',
      'new_chat': 'புதிய அரட்டை',
      'chat_history': 'அரட்டை வரலாறு',
      'back_to_chat': 'அரட்டைக்குத் திரும்பு',
      'view_analysis': 'பகுப்பாய்வைப் பார்',
      'download_chat': 'அரட்டையைப் பதிவிறக்கவும்',
      'share_chat': 'அரட்டையைப் பகிரவும்',
      'type_message': 'செய்தியைத் தட்டச்சு செய்க...',
      'select_mode': 'பயன்முறையைத் தேர்ந்தெடுக்கவும்',
      'stop_listening': 'கேட்பதை நிறுத்து',
      'start_listening': 'கேட்கத் தொடங்கு',
      'female': 'பெண்',
      'male': 'ஆண்',
      'no_system_voices': 'கணினி குரல்கள் எதுவும் காணப்படவில்லை. உங்கள் சாதன அமைப்புகளைச் சரிபார்க்கவும்.',
      'selected_voice_msg': 'தேர்ந்தெடுக்கப்பட்ட குரல்: ',
      'preview_failed': 'முன்னோட்டம் தோல்வியடைந்தது: ',
      'no_voices_available': 'குரல்கள் எதுவும் கிடைக்கவில்லை',
      'unknown': 'தெரியவில்லை',
      'select': 'தேர்ந்தெடு',
      'retry': 'மீண்டும் முயற்சி செய்',
      'hello_voice': 'வணக்கம், நான் {name}. இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?',
      'email': 'மின்னஞ்சல்',
      'phone': 'தொலைபேசி',
      'dob': 'பிறந்த தேதி',
      'user_name': 'பயனர் பெயர்',
      'edit_profile': 'சுயவிவரத்தைத் திருத்து',
      'tap_to_change': 'புகைப்படத்தை மாற்ற தட்டவும்',
      'username': 'பயனர் பெயர்',
      'phone_number': 'தொலைபேசி எண்',
      'save_changes': 'மாற்றங்களைச் சேமி',
      'profile_updated': 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
      'failed_update': 'சுயவிவரத்தைப் புதுப்பிக்கத் தவறிவிட்டது',
      'enter_username': 'பயனர் பெயரை உள்ளிடவும்',
      'enter_email': 'மின்னஞ்சலை உள்ளிடவும்',
      'enter_valid_email': 'செல்லுபடியாகும் மின்னஞ்சலை உள்ளிடவும்',
      'enter_phone': 'தொலைபேசி எண்ணை உள்ளிடவும்',
      'select_dob': 'பிறந்த தேதியைத் தேர்ந்தெடுக்கவும்',
      'relationship': 'உறவு',
      'cancel': 'ரத்து செய்',
      'save': 'சேமி',
      'delete': 'நீக்கு',
      'delete_account_confirm': 'உங்கள் கணக்கை நீக்க விரும்புகிறீர்களா? இந்தச் செயலை மாற்ற முடியாது மற்றும் உங்கள் எல்லா தரவும் இழக்கப்படும்.',
      'account_deleted': 'கணக்கு வெற்றிகரமாக நீக்கப்பட்டது.',
      'failed_delete_account': 'கணக்கை நீக்கத் தவறிவிட்டது.',
      'app_version': 'பயன்பாட்டு பதிப்பு',
      'analysis_dashboard': 'பகுப்பாய்வு டாஷ்போர்டு',
      'insights': 'நுண்ணறிவுகள்',
      'positive': 'நேர்மறை',
      'negative': 'எதிர்மறை',
      'mostly_positive_msg': 'சிறந்த வேலை! நேர்மறையான அதிர்வுகளைத் தொடருங்கள்! 😊',
      'mostly_negative_msg': 'கொஞ்சம் சவாலானதா? பரவாயில்லை, தொடருங்கள்! 💪',
      'emotion_trend': 'காலப்போக்கில் உணர்ச்சி போக்கு',
      'daily_mood_timeline': 'தினசரி மனநிலை காலவரிசை',
      'score': 'மதிப்பெண்',
      'excellent': 'சிறப்பானது',
      'good': 'நல்லது',
      'moderate': 'மிதமானது',
      'needs_attention': 'கவனம் தேவை',
      'score_basis': 'உங்கள் சமீபத்திய தொடர்புகளின் அடிப்படையில்.',
      'no_data': 'இந்த காலத்திற்கு தரவு இல்லை',
      'morning': 'காலை',
      'afternoon': 'மதியம்',
      'evening': 'மாலை',
      'night': 'இரவு',
      'happy': 'மகிழ்ச்சி',
      'sad': 'சோகம்',
      'angry': 'கோபம்',
      'calm': 'அமைதி',
      'no_avatar_selected': 'அவதாரம் தேர்ந்தெடுக்கப்படவில்லை',
      'default_avatar_msg': 'வணக்கம்! நான் உங்களுக்கு உதவ இங்கே இருக்கிறேன்.',
      'select_avatar': 'அவதாரத்தைத் தேர்ந்தெடுக்கவும்',
      'no_avatars_found': 'அவதாரங்கள் எதுவும் கிடைக்கவில்லை.\nதொடங்குவதற்கு ஒன்றை உருவாக்கவும்!',
      'avatar_set_active': 'அவதாரம் செயலில் உள்ளது!',
      'avatar_deleted': 'அவதாரம் வெற்றிகரமாக நீக்கப்பட்டது',
      'delete_avatar_confirm': 'இந்த அவதாரத்தை நீக்க விரும்புகிறீர்களா?',
      'create_new_avatar': 'புதிய அவதாரத்தை உருவாக்கு',
      'error_fetching_avatars': 'அவதாரங்களைப் பெறுவதில் பிழை',
      'error_setting_active_avatar': 'செயலில் உள்ள அவதாரத்தை அமைப்பதில் பிழை',
      'error_deleting_avatar': 'அவதாரத்தை நீக்குவதில் பிழை',
      'create_your_avatar': 'உங்கள் அவதாரத்தை உருவாக்குங்கள்',
      'error_saving_avatar': 'அவதாரத்தைச் சேமிப்பதில் பிழை',
      'close_and_go_home': 'மூடிவிட்டு முகப்புக்குச் செல்லவும்',
      'my_new_avatar': 'எனது புதிய அவதாரம்',
      'select_ai_mode': 'AI பயன்முறையைத் தேர்ந்தெடுக்கவும்',
      'funny_desc': 'நகைச்சுவை உணர்வு மற்றும் நகைச்சுவைகளுடன் கூடிய AI.',
      'search_desc': 'உண்மைகள் மற்றும் தகவல்களைக் கண்டறிவதில் கவனம் செலுத்துகிறது.',
      'mental_health_desc': 'பரிவு மற்றும் ஆதரவான கேட்பவர்.',
      'study_desc': 'கற்றல் மற்றும் விளக்கங்களுக்கு உதவுகிறது.',
      'snooze': 'ஸ்னூஸ்',
      'stop': 'நிறுத்து',
      'minutes': 'நிமிடங்கள்',
      'reminder_msg_prefix': 'இது உங்கள் நினைவூட்டல்',
      'intelligent_companion': 'உங்கள் புத்திசாலித்தனமான துணை',
      'mic_access': 'மைக்ரோஃபோன் அணுகல்',
      'mic_desc': 'உங்கள் அவதார் துணை உங்கள் பேச்சைக் கேட்டு உங்களுக்குப் பதிலளிக்க மைக்ரோஃபோன் அணுகல் எங்களுக்குத் தேவை.',
      'notif_access': 'அறிவிப்புகள்',
      'notif_desc': 'உங்கள் துணையிடமிருந்து முக்கியமான நினைவூட்டல்கள் மற்றும் விழிப்பூட்டல்களைப் பெற அறிவிப்புகளை இயக்கவும்.',
      'overlay_access': 'பிற பயன்பாடுகளுக்கு மேல் காண்பி',
      'overlay_desc': 'பூட்டுத் திரையில் கூட, நினைவூட்டல் தூண்டப்படும்போது அவதார் பிற பயன்பாடுகளுக்கு மேல் தோன்ற அனுமதிக்கவும்.',
      'battery_access': 'பேட்டரி மேம்படுத்தல்',
      'battery_desc': 'நினைவூட்டல்கள் சரியான நேரத்தில் ஒலிப்பதை உறுதிசெய்ய, பயன்பாட்டை எந்தக் கட்டுப்பாடுகளும் இன்றி பின்னணியில் இயங்க அனுமதிக்கவும்.',
      'alarm_access': 'துல்லியமான அலாரங்கள்',
      'alarm_desc': 'உங்கள் நினைவூட்டல்கள் சரியாக சரியான நேரத்தில் தூண்டப்படுவதை உறுதிசெய்ய, துல்லியமான அலாரங்களை அமைக்க பயன்பாட்டை அனுமதிக்கவும்.',
      'location_access': 'இருப்பிட அணுகல்',
      'location_desc': 'விருப்பமானது: உங்களுக்கு அருகிலுள்ள மருத்துவர்கள் மற்றும் சேவைகளைக் கண்டறிய உங்கள் இருப்பிடத்தைப் பயன்படுத்துகிறோம்.',
      'allow_access': 'அணுகலை அனுமதி',
      'skip_for_now': 'இப்போதைக்குத் தவிர்க்கவும்',
      'no_thanks': 'வேண்டாம்',
      'permission_required': 'அனுமதி தேவை',
      'permission_desc': 'இந்த அம்சம் செயல்பட அனுமதி தேவை. பயன்பாட்டு அமைப்புகளில் அதை இயக்கவும்.',
      'open_settings': 'அமைப்புகளைத் திறக்கவும்',
      'sign_in_continue': 'தொடர உள்நுழையவும்',
      'login_failed': 'உள்நுழைவு தோல்வியடைந்தது',
      'enter_email': 'மின்னஞ்சலை உள்ளிடவும்',
      'enter_valid_email': 'செல்லுபடியாகும் மின்னஞ்சலை உள்ளிடவும்',
      'enter_password': 'கடவுச்சொல்லை உள்ளிடவும்',
      'password_min_length': 'கடவுச்சொல் குறைந்தது 6 எழுத்துகளாக இருக்க வேண்டும்',
      'no_account_signup': "கணக்கு இல்லையா? பதிவு செய்யவும்",
      'login_caps': 'உள்நுழை',
      'create_account': 'கணக்கை உருவாக்கு',
      'join_start_chatting': 'அரட்டையடிக்க எங்களுடன் இணையுங்கள்',
      'full_name': 'முழு பெயர்',
      'phone_number': 'தொலைபேசி எண்',
      'enter_name': 'உங்கள் பெயரை உள்ளிடவும்',
      'enter_phone': 'தொலைபேசி எண்ணை உள்ளிடவும்',
      'enter_valid_phone': 'செல்லுபடியாகும் 10 இலக்க தொலைபேசி எண்ணை உள்ளிடவும்',
      'select_dob': 'உங்கள் பிறந்த தேதியைத் தேர்ந்தெடுக்கவும்',
      'registration_success': 'பதிவு வெற்றிகரமாக முடிந்தது!',
      'registration_failed': 'பதிவு தோல்வியடைந்தது',
      'already_account_signin': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக',
      'register_caps': 'பதிவு செய்',
      'avatars': 'அவதாரங்கள்',
      'active': 'செயலில்',
      'exit': 'வெளியேறு',
      'no_chat_history': 'அரட்டை வரலாறு எதுவும் இல்லை.',
      'chat_downloaded_preview': 'அரட்டை பதிவிறக்கம் செய்யப்பட்டது (முன்னோட்டம்)',
      'delete_chat': 'அரட்டையை நீக்கு',
      'delete_chat_confirm': 'இந்த அரட்டை வரலாற்றை நீக்க விரும்புகிறீர்களா?',
      'conversation_deleted': 'உரையாடல் நீக்கப்பட்டது',
      'no_reminders_set': 'நினைவூட்டல்கள் எதுவும் அமைக்கப்படவில்லை.',
      'repeat_none': 'மீண்டும்: இல்லை',
      'edit': 'திருத்து',
      'delete': 'நீக்கு',
      'reminder_deleted': 'நினைவூட்டல் நீக்கப்பட்டது',
      'chat': 'அரட்டை',
      'searching': 'தேடுகிறது',
      'this_week': 'இந்த வாரம்',
      'last_week': 'கடந்த வாரம்',
      'you': 'நீங்கள்',
      'ai': 'AI',
      'chat_conversation_subject': 'எனது AI அரட்டை உரையாடல்',
      'chat_conversation_header': 'AI அரட்டை உரையாடல்',
      'notifications': 'அறிவிப்புகள்',
      'no_notifications': 'புதிய அறிவிப்புகள் இல்லை',
      'delete_selected': 'தேர்ந்தெடுக்கப்பட்டதை நீக்கு',
      'select_all': 'அனைத்தையும் தேர்ந்தெடு',
      'deselect_all': 'அனைத்தையும் நீக்கு',
      'items_selected': 'உருப்படிகள் தேர்ந்தெடுக்கப்பட்டன',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  final Locale locale;

  const AppLocalizationsDelegate(this.locale);

  @override
  bool isSupported(Locale locale) => ['en', 'es', 'fr', 'hi', 'de', 'ta'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(this.locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => old.locale != locale;
}
